name: Apply Terraform

on:
  push:
    paths:
      - 'platform/terraform/**'

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: platform/terraform
      run: terraform init
      env:
        TF_VAR_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Apply Terraform
      working-directory: platform/terraform
      run: terraform apply -auto-approve -var "personal_access_token=${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      env:
        TF_VAR_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}